social_media:
  facebook_share:
    text: 'Jaa Facebook-palvelussa'
    attributes: "target|_blank\r\nclass|facebook-share"
  linkedin:
    api_url: 'https://www.linkedin.com/sharing/share-offsite/?url=[current-page:url]'
    text: 'Jaa LinkedIn-palvelussa'
    attributes: "target|_blank\r\nclass|linkedin"
  twitter:
    api_url: 'https://x.com/intent/post?url=[current-page:url]&status=[current-page:title]+[current-page:url]'
    text: 'Jaa X-palvelussa'
    attributes: "target|_blank\r\nclass|twitter"
  email:
    text: 'Lähetä sivu sähköpostitse'
