display:
  default:
    display_options:
      title: 'Etsi avustusta'
      exposed_form:
        options:
          submit_button: Etsi
          reset_button_label: Tyhjennä
      empty:
        area:
          content:
            value: '<h3>Tuloksia ei löytynyt</h3>'
            format: full_html
      filters:
        search_api_fulltext:
          expose:
            label: 'Tai etsi hakusanalla'
            placeholder: 'Etsi nimellä tai hakusanalla, esim toiminta-avustus'
        canonical_target_group_select:
          expose:
            label: 'Valitse kohderyhmä'
        canonical_subvention_type_select:
          expose:
            label: 'Millaiseen toimintaan haet avustusta?'
        canonical_applicant_type_select:
          expose:
            label: 'Avustuksen hakija'
      header:
        result:
          content: '<strong>@total</strong> hakutulosta'
  search_page:
    display_options:
      menu:
        title: 'Etsi avustusta'
