name: 'Grants application'
type: module
description: 'Provides the improved form implementation'
package: 'helfi'
core_version_requirement: ^10 || ^11
dependencies:
  - helfi_av:helfi_av
  - helfi_atv:helfi_atv
  - grants_profile
  - helfi_helsinki_profiili
  - content_lock:content_lock
'interface translation project': grants_application
'interface translation server pattern': modules/custom/grants_application/translations/%language.po
