display:
  default:
    display_options:
      title: 'Sök understöd'
      exposed_form:
        options:
          submit_button: Sök
          reset_button_label: Töm
      empty:
        area:
          content:
            value: '<h3>Inga resultat hittades</h3>'
            format: full_html
      filters:
        search_api_fulltext:
          expose:
            label: Nyckelord
            placeholder: 'Sök på namn eller sökterm, till exempel verksamhetsunderstöd'
        canonical_target_group_select:
          expose:
            label: Målgrupp
        canonical_subvention_type_select:
          expose:
            label: 'Vilken typ av verksamhet ansöker du om understöd?'
        canonical_applicant_type_select:
          expose:
            label: Sökande
      header:
        result:
          content: '<strong>@total</strong> sökresultat'
  search_page:
    display_options:
      menu:
        title: 'Sök understöd'
